apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: nuvolaris
  labels:
    app: spark
    component: spark-master
spec:
  type: NodePort
  selector:
    app: spark
    component: spark-master
  ports:
    - name: master
      port: 7077
      targetPort: 7077
      nodePort: 30707
      protocol: TCP
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30808
      protocol: TCP