apiVersion: v1
kind: Service
metadata:
  name: spark-history
  namespace: nuvolaris
  labels:
    app: spark
    component: spark-history
spec:
  type: ClusterIP
  selector:
    app: spark
    component: spark-history
  ports:
  - name: webui
    port: 18080
    targetPort: 18080
    protocol: TCP
